services:
  database:
    image: postgres:18
    container_name: sql_project_db
    environment:
      POSTGRES_DB: analytics
      POSTGRES_USER: analyst
      POSTGRES_PASSWORD: analyst
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: